---
# tasks file for nginx
- name: install nginx & wordpress
  dnf:
    name: "{{ item }}"
    state: present
  loop:
    - nginx
    - tar
    - wget
    - php
    - php-curl
    - php-mysqlnd
    - php-gd
    - php-cli

- name: download wordpress
  get_url:
    url: https://ko.wordpress.org/wordpress-6.8-ko_KR.tar.gz
    dest: '/home/ysjang/'

- name: extract wordpress
  unarchive:
    src: '/home/ysjang/wordpress-6.8-ko_KR.tar.gz'
    dest: '/home/ysjang/'
    remote_src: yes
    owner: nginx
    group: nginx
    mode: 0755

- name: copy wordpress to /usr/share/nginx/html
  copy:
    src: /home/ysjang/wordpress/
    dest: /usr/share/nginx/html/
    remote_src: yes
    owner: nginx
    group: nginx
    mode: 0755
    force: yes

- name: copy wp-config-sample.php wp-config.php
  copy:
    src: /usr/share/nginx/html/wp-config-sample.php
    dest: /usr/share/nginx/html/wp-config.php
    remote_src: yes
    owner: nginx
    group: nginx
    mode: 0644
    force: yes

- name: change www.conf
  copy:
    src: www.conf.j2
    dest: /etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
    force: yes

- name: change nginx.conf
  copy:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
    force: yes

- name: change wp-config.php
  replace:
    path: /usr/share/nginx/html/wp-config.php
    regexp: "{{ item.from }}"
    replace: "{{ item.to }}"
  loop:
    - { from: 'database_name_here', to: "{{ db_name }}" }
    - { from: 'username_here', to: "{{ username }}" }
    - { from: 'password_here', to: "{{ password }}" }
    - { from: 'localhost', to: "{{ localhost }}" }
  notify:
    - start nginx
    - start php-fpm